import React, { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, CheckCircle2, ChevronDown, ChevronRight, Edit3, Eye, EyeOff, GitBranch, GripVertical, Loader2, Plus, RefreshCw, Save, Settings2, Sparkles, Trash2, X } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { ConditionBuilder } from "../components/habits/ConditionBuilder";
import { habitConfigurationService, HABIT_CONFIG_PERMISSIONS } from "../services/habitConfigurationService";
import { Habit, HabitConfiguration, HabitIndicator, IndicatorOption } from "../types/habitConfiguration";

const inputClass = "mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none transition focus:border-sky-400 focus:ring-4 focus:ring-sky-50";
const labelClass = "text-xs font-extrabold uppercase tracking-wide text-slate-600";

const Modal: React.FC<{ title: string; children: React.ReactNode; onClose: () => void }> = ({ title, children, onClose }) => (
  <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-sm">
    <div className="w-full max-w-lg rounded-3xl bg-white shadow-2xl ring-1 ring-slate-200">
      <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h3 className="text-lg font-black text-slate-900">{title}</h3><button type="button" onClick={onClose} className="rounded-xl p-2 text-slate-400 hover:bg-slate-100"><X className="h-4 w-4" /></button></div>
      <div className="p-5">{children}</div>
    </div>
  </div>
);

export const HabitConfigurationPage: React.FC = () => {
  const { user, hasPermission } = useAuth();
  const canRead = user ? (user.role === "super_admin" || hasPermission(HABIT_CONFIG_PERMISSIONS.read)) : false;
  const canWrite = user ? (user.role === "super_admin" || hasPermission(HABIT_CONFIG_PERMISSIONS.write)) : false;
  const schoolId = user?.schoolId ?? "sch-101";
  const [config, setConfig] = useState<HabitConfiguration | null>(null);
  const [selectedHabitId, setSelectedHabitId] = useState("");
  const [selectedIndicatorId, setSelectedIndicatorId] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [modal, setModal] = useState<"habit" | "indicator" | "option" | null>(null);
  const [editingHabit, setEditingHabit] = useState<Habit | null>(null);
  const [editingIndicator, setEditingIndicator] = useState<HabitIndicator | null>(null);
  const [editingOption, setEditingOption] = useState<IndicatorOption | null>(null);
  const [conditionOpen, setConditionOpen] = useState(false);

  const selectedHabit = useMemo(() => config?.habits.find((h) => h.id === selectedHabitId) ?? null, [config, selectedHabitId]);
  const selectedIndicator = useMemo(() => selectedHabit?.indicators.find((i) => i.id === selectedIndicatorId) ?? null, [selectedHabit, selectedIndicatorId]);

  const load = useCallback(async () => {
    if (!user || !canRead) { setLoading(false); return; }
    setLoading(true); setError("");
    try {
      const result = await habitConfigurationService.getConfiguration(user, schoolId);
      setConfig(result);
      setSelectedHabitId((current) => result.habits.some((h) => h.id === current) ? current : result.habits[0]?.id ?? "");
    } catch (err) { setError(err instanceof Error ? err.message : "Gagal memuat konfigurasi kebiasaan."); }
    finally { setLoading(false); }
  }, [canRead, schoolId, user]);

  useEffect(() => { void load(); }, [load]);
  useEffect(() => { setSelectedIndicatorId((current) => selectedHabit?.indicators.some((i) => i.id === current) ? current : selectedHabit?.indicators[0]?.id ?? ""); }, [selectedHabit]);

  const update = (result: HabitConfiguration) => { setConfig(result); setNotice("Perubahan tersimpan sebagai konfigurasi draft."); window.setTimeout(() => setNotice(""), 2600); };
  const runSave = async (fn: () => Promise<HabitConfiguration>, success = "Perubahan berhasil disimpan.") => { setSaving(true); setError(""); try { const result = await fn(); setConfig(result); setNotice(success); window.setTimeout(() => setNotice(""), 2600); setModal(null); } catch (err) { setError(err instanceof Error ? err.message : "Gagal menyimpan konfigurasi."); } finally { setSaving(false); } };

  const moveHabit = async (index: number, delta: number) => { if (!config || !canWrite) return; const to = index + delta; if (to < 0 || to >= config.habits.length) return; setSaving(true); try { update(await habitConfigurationService.reorderHabits(user!, schoolId, index, to)); } catch (err) { setError(err instanceof Error ? err.message : "Gagal mengubah urutan."); } finally { setSaving(false); } };
  const moveIndicator = async (index: number, delta: number) => { if (!config || !selectedHabit || !canWrite) return; const to = index + delta; if (to < 0 || to >= selectedHabit.indicators.length) return; setSaving(true); try { update(await habitConfigurationService.reorderIndicators(user!, schoolId, selectedHabit.id, index, to)); } catch (err) { setError(err instanceof Error ? err.message : "Gagal mengubah urutan indikator."); } finally { setSaving(false); } };

  if (!canRead) return <div className="rounded-3xl border border-rose-100 bg-white p-10 text-center shadow-sm"><AlertCircle className="mx-auto h-10 w-10 text-rose-500" /><h1 className="mt-4 text-xl font-extrabold text-slate-900">Akses tidak tersedia</h1><p className="mx-auto mt-2 max-w-lg text-sm text-slate-500">Konfigurasi 7 Kebiasaan mengikuti authorization backend dan scope sekolah.</p></div>;

  return (
    <div className="min-h-full space-y-5">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-violet-50 px-3 py-1 text-[11px] font-extrabold text-violet-700"><Settings2 className="h-3.5 w-3.5" /> Master 7 Kebiasaan</div><h1 className="text-2xl font-black tracking-tight text-slate-900">Konfigurasi 7 Kebiasaan</h1><p className="mt-1 max-w-3xl text-sm leading-relaxed text-slate-500">Data kebiasaan, indikator, pilihan, poin/EXP, urutan, dan kondisi dibaca dari API. UI tidak mengunci struktur menjadi tujuh kolom atau indikator tetap.</p></div>
        <div className="flex flex-wrap gap-2">{config && <div className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-extrabold text-slate-600">v{config.version} · {config.status === "published" ? "Published" : "Draft"}</div>}<button type="button" onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-extrabold text-slate-700 hover:bg-slate-50"><RefreshCw className="h-4 w-4" /> Refresh</button>{canWrite && <button type="button" disabled={saving} onClick={() => void runSave(() => habitConfigurationService.publish(user!, schoolId), "Konfigurasi berhasil dipublish.")} className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-xs font-extrabold text-white shadow-sm hover:bg-violet-700 disabled:opacity-50"><Sparkles className="h-4 w-4" /> Publish versi</button>}</div>
      </div>

      {error && <div className="flex items-start gap-3 rounded-2xl border border-rose-100 bg-rose-50 p-4 text-sm text-rose-700"><AlertCircle className="mt-0.5 h-5 w-5 shrink-0" /><div className="flex-1"><p className="font-extrabold">Terjadi kesalahan</p><p className="mt-0.5 text-xs">{error}</p></div><button type="button" onClick={() => setError("")} className="text-xs font-bold">Tutup</button></div>}
      {notice && <div className="flex items-center gap-2 rounded-2xl border border-emerald-100 bg-emerald-50 p-4 text-sm font-bold text-emerald-700"><CheckCircle2 className="h-5 w-5" /> {notice}</div>}

      {loading ? <div className="grid gap-4 lg:grid-cols-[300px_1fr]"><div className="h-[620px] animate-pulse rounded-3xl bg-white shadow-sm ring-1 ring-slate-100" /><div className="h-[620px] animate-pulse rounded-3xl bg-white shadow-sm ring-1 ring-slate-100" /></div> : config && <div className="grid gap-4 lg:grid-cols-[310px_1fr]">
        <section className="rounded-3xl bg-white p-4 shadow-sm ring-1 ring-slate-100">
          <div className="flex items-center justify-between"><div><p className="text-xs font-extrabold uppercase tracking-wider text-slate-400">Master</p><h2 className="mt-1 text-lg font-black text-slate-900">Kebiasaan</h2></div>{canWrite && <button type="button" onClick={() => { setEditingHabit(null); setModal("habit"); }} className="rounded-xl bg-sky-50 p-2 text-sky-600 hover:bg-sky-100"><Plus className="h-4 w-4" /></button>}</div>
          <div className="mt-4 space-y-2">{config.habits.map((habit, index) => <div key={habit.id} className={`group flex items-center gap-2 rounded-2xl border p-2 transition ${habit.id === selectedHabitId ? "border-sky-200 bg-sky-50" : "border-slate-100 hover:bg-slate-50"}`}><button type="button" onClick={() => setSelectedHabitId(habit.id)} className="flex min-w-0 flex-1 items-center gap-3 text-left"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-white text-xs font-black text-sky-600 shadow-sm">{index + 1}</span><span className="min-w-0"><span className="block truncate text-sm font-extrabold text-slate-800">{habit.name}</span><span className="block text-[11px] text-slate-400">{habit.indicators.length} indikator</span></span></button>{canWrite && <div className="flex items-center opacity-0 transition group-hover:opacity-100"><button type="button" disabled={index === 0} onClick={() => void moveHabit(index, -1)} className="p-1 text-slate-400 disabled:opacity-20">↑</button><button type="button" disabled={index === config.habits.length - 1} onClick={() => void moveHabit(index, 1)} className="p-1 text-slate-400 disabled:opacity-20">↓</button></div>}</div>)}</div>
          <div className="mt-4 rounded-2xl bg-slate-50 p-3 text-xs leading-relaxed text-slate-500"><strong className="text-slate-700">Data-driven:</strong> daftar ini berasal dari mock API dan nanti dapat langsung diganti endpoint Habit API tanpa mengubah komponen.</div>
        </section>

        <section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-100">
          {selectedHabit ? <>
            <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><div className="flex items-center gap-2"><span className="rounded-full bg-sky-50 px-2.5 py-1 text-[11px] font-black text-sky-700">Urutan {selectedHabit.order}</span><span className={`rounded-full px-2.5 py-1 text-[11px] font-black ${selectedHabit.active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{selectedHabit.active ? "Aktif" : "Nonaktif"}</span></div><h2 className="mt-2 text-xl font-black text-slate-900">{selectedHabit.name}</h2><p className="mt-1 text-sm text-slate-500">{selectedHabit.description}</p></div>{canWrite && <button type="button" onClick={() => { setEditingHabit(selectedHabit); setModal("habit"); }} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-extrabold text-slate-700 hover:bg-slate-50"><Edit3 className="h-4 w-4" /> Edit kebiasaan</button>}</div>
            <div className="mt-5 flex items-center justify-between"><div><p className="text-xs font-extrabold uppercase tracking-wider text-slate-400">Indikator</p><p className="mt-1 text-xs text-slate-500">Susun urutan dan atur pilihan jawaban tanpa mengubah struktur aplikasi.</p></div>{canWrite && <button type="button" onClick={() => { setEditingIndicator(null); setModal("indicator"); }} className="inline-flex items-center gap-2 rounded-xl bg-sky-600 px-3 py-2 text-xs font-extrabold text-white"><Plus className="h-4 w-4" /> Tambah indikator</button>}</div>
            <div className="mt-4 space-y-3">{selectedHabit.indicators.map((indicator, index) => <div key={indicator.id} className={`rounded-2xl border p-4 ${selectedIndicatorId === indicator.id ? "border-sky-200 bg-sky-50/40" : "border-slate-100"}`}>
              <div className="flex items-start gap-3"><div className="mt-1 text-slate-300"><GripVertical className="h-4 w-4" /></div><button type="button" onClick={() => setSelectedIndicatorId(indicator.id)} className="min-w-0 flex-1 text-left"><div className="flex flex-wrap items-center gap-2"><span className="text-[11px] font-black text-slate-400">#{index + 1}</span><h3 className="text-sm font-black text-slate-800">{indicator.name}</h3>{indicator.required && <span className="rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-black text-amber-700">Wajib</span>}{indicator.conditions.length > 0 && <span className="inline-flex items-center gap-1 rounded-full bg-violet-50 px-2 py-0.5 text-[10px] font-black text-violet-700"><GitBranch className="h-3 w-3" /> Conditional</span>}</div><p className="mt-1 text-xs text-slate-500">{indicator.description || "Tanpa deskripsi"}</p></button>{canWrite && <div className="flex items-center gap-1"><button type="button" disabled={index === 0} onClick={() => void moveIndicator(index, -1)} className="rounded-lg p-1.5 text-slate-400 hover:bg-white disabled:opacity-20">↑</button><button type="button" disabled={index === selectedHabit.indicators.length - 1} onClick={() => void moveIndicator(index, 1)} className="rounded-lg p-1.5 text-slate-400 hover:bg-white disabled:opacity-20">↓</button><button type="button" onClick={() => { setEditingIndicator(indicator); setModal("indicator"); }} className="rounded-lg p-1.5 text-slate-500 hover:bg-white"><Edit3 className="h-3.5 w-3.5" /></button></div>}</div>
              {selectedIndicatorId === indicator.id && <div className="mt-4 border-t border-slate-100 pt-4">
                <div className="flex items-center justify-between"><div><p className="text-xs font-extrabold uppercase tracking-wide text-slate-400">Pilihan jawaban</p><p className="mt-1 text-xs text-slate-500">Setiap pilihan dapat memiliki Poin dan EXP sendiri.</p></div>{canWrite && <button type="button" onClick={() => { setEditingOption(null); setModal("option"); }} className="inline-flex items-center gap-1.5 rounded-xl bg-white px-3 py-2 text-xs font-extrabold text-sky-700 shadow-sm ring-1 ring-sky-100"><Plus className="h-3.5 w-3.5" /> Tambah pilihan</button>}</div>
                <div className="mt-3 grid gap-2 md:grid-cols-2">{indicator.options.map((opt) => <div key={opt.id} className="flex items-center gap-3 rounded-xl border border-slate-100 bg-white p-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-800">{opt.label}</p><p className="mt-0.5 text-[11px] text-slate-400">{opt.points} poin · {opt.exp} EXP</p></div><span className={`text-[10px] font-black ${opt.active ? "text-emerald-600" : "text-slate-400"}`}>{opt.active ? "Aktif" : "Nonaktif"}</span>{canWrite && <button type="button" onClick={() => { setEditingOption(opt); setModal("option"); }} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-50"><Edit3 className="h-3.5 w-3.5" /></button>}</div>)}</div>
                {canWrite && <div className="mt-4"><button type="button" onClick={() => setConditionOpen((v) => !v)} className="inline-flex items-center gap-2 text-xs font-extrabold text-violet-700"><ChevronRight className={`h-4 w-4 transition ${conditionOpen ? "rotate-90" : ""}`} /> Atur conditional indicator</button>{conditionOpen && <div className="mt-3"><ConditionBuilder indicators={selectedHabit.indicators} target={indicator} onSave={(sourceIndicatorId, sourceOptionId) => void runSave(() => habitConfigurationService.saveCondition(user!, schoolId, selectedHabit.id, indicator.id, { sourceIndicatorId, sourceOptionId }), "Kondisi indikator berhasil disimpan.")} onRemove={() => void runSave(() => habitConfigurationService.removeCondition(user!, schoolId, selectedHabit.id, indicator.id), "Kondisi indikator dihapus.")} /></div>}</div>}
              </div>}
            </div>)}</div>
          </> : <div className="flex min-h-[500px] items-center justify-center text-center"><div><Settings2 className="mx-auto h-10 w-10 text-slate-300" /><h2 className="mt-3 text-lg font-black text-slate-800">Pilih kebiasaan</h2><p className="mt-1 text-sm text-slate-500">Pilih master kebiasaan dari panel kiri.</p></div></div>}
        </section>
      </div>}

      {config && <div className="rounded-2xl border border-slate-200 bg-white p-4 text-xs leading-relaxed text-slate-500 shadow-sm"><strong className="text-slate-700">Catatan versioning:</strong> publish menghasilkan versi konfigurasi baru. Histori submission/jawaban dan transaksi Poin/EXP tetap menjadi sumber histori dan tidak boleh berubah karena konfigurasi aktif berubah.</div>}

      {modal === "habit" && <HabitModal editing={editingHabit} saving={saving} onClose={() => setModal(null)} onSubmit={(value) => void runSave(() => habitConfigurationService.saveHabit(user!, schoolId, editingHabit?.id ?? null, value), editingHabit ? "Kebiasaan diperbarui." : "Kebiasaan ditambahkan.")} />}
      {modal === "indicator" && selectedHabit && <IndicatorModal editing={editingIndicator} saving={saving} onClose={() => setModal(null)} onSubmit={(value) => void runSave(() => habitConfigurationService.saveIndicator(user!, schoolId, selectedHabit.id, editingIndicator?.id ?? null, value), editingIndicator ? "Indikator diperbarui." : "Indikator ditambahkan.")} />}
      {modal === "option" && selectedHabit && selectedIndicator && <OptionModal editing={editingOption} saving={saving} onClose={() => setModal(null)} onSubmit={(value) => void runSave(() => habitConfigurationService.saveOption(user!, schoolId, selectedHabit.id, selectedIndicator.id, editingOption?.id ?? null, value), editingOption ? "Pilihan diperbarui." : "Pilihan ditambahkan.")} />}
    </div>
  );
};

const HabitModal: React.FC<{ editing: Habit | null; saving: boolean; onClose: () => void; onSubmit: (v: {name:string;description?:string;active:boolean}) => void }> = ({ editing, saving, onClose, onSubmit }) => { const [name,setName]=useState(editing?.name??""); const [description,setDescription]=useState(editing?.description??""); const [active,setActive]=useState(editing?.active??true); return <Modal title={editing ? "Edit kebiasaan" : "Tambah kebiasaan"} onClose={onClose}><form onSubmit={(e)=>{e.preventDefault(); if(name.trim()) onSubmit({name,description,active});}} className="space-y-4"><label className={labelClass}>Nama kebiasaan<input autoFocus value={name} onChange={e=>setName(e.target.value)} className={inputClass} placeholder="Contoh: Kebiasaan baru" /></label><label className={labelClass}>Deskripsi<textarea value={description} onChange={e=>setDescription(e.target.value)} className={`${inputClass} min-h-24`} /></label><label className="flex items-center gap-2 text-sm font-bold text-slate-700"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)} /> Aktif</label><button disabled={saving || !name.trim()} className="w-full rounded-xl bg-sky-600 py-3 text-xs font-extrabold text-white disabled:opacity-40">{saving ? "Menyimpan..." : "Simpan"}</button></form></Modal>; };
const IndicatorModal: React.FC<{ editing: HabitIndicator | null; saving: boolean; onClose: () => void; onSubmit: (v: {name:string;description?:string;required:boolean;active:boolean}) => void }> = ({ editing, saving, onClose, onSubmit }) => { const [name,setName]=useState(editing?.name??""); const [description,setDescription]=useState(editing?.description??""); const [required,setRequired]=useState(editing?.required??true); const [active,setActive]=useState(editing?.active??true); return <Modal title={editing ? "Edit indikator" : "Tambah indikator"} onClose={onClose}><form onSubmit={(e)=>{e.preventDefault(); if(name.trim()) onSubmit({name,description,required,active});}} className="space-y-4"><label className={labelClass}>Nama indikator<input autoFocus value={name} onChange={e=>setName(e.target.value)} className={inputClass} /></label><label className={labelClass}>Deskripsi<textarea value={description} onChange={e=>setDescription(e.target.value)} className={`${inputClass} min-h-24`} /></label><div className="flex gap-4"><label className="flex items-center gap-2 text-sm font-bold text-slate-700"><input type="checkbox" checked={required} onChange={e=>setRequired(e.target.checked)} /> Wajib</label><label className="flex items-center gap-2 text-sm font-bold text-slate-700"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)} /> Aktif</label></div><button disabled={saving || !name.trim()} className="w-full rounded-xl bg-sky-600 py-3 text-xs font-extrabold text-white disabled:opacity-40">{saving ? "Menyimpan..." : "Simpan"}</button></form></Modal>; };
const OptionModal: React.FC<{ editing: IndicatorOption | null; saving: boolean; onClose: () => void; onSubmit: (v: {label:string;points:number;exp:number;active:boolean}) => void }> = ({ editing, saving, onClose, onSubmit }) => { const [label,setLabel]=useState(editing?.label??""); const [points,setPoints]=useState(String(editing?.points??0)); const [exp,setExp]=useState(String(editing?.exp??0)); const [active,setActive]=useState(editing?.active??true); return <Modal title={editing ? "Edit pilihan" : "Tambah pilihan"} onClose={onClose}><form onSubmit={(e)=>{e.preventDefault(); const p=Number(points),x=Number(exp); if(label.trim() && p>=0 && x>=0) onSubmit({label,points:p,exp:x,active});}} className="space-y-4"><label className={labelClass}>Label pilihan<input autoFocus value={label} onChange={e=>setLabel(e.target.value)} className={inputClass} /></label><div className="grid grid-cols-2 gap-3"><label className={labelClass}>Poin<input type="number" min="0" value={points} onChange={e=>setPoints(e.target.value)} className={inputClass} /></label><label className={labelClass}>EXP<input type="number" min="0" value={exp} onChange={e=>setExp(e.target.value)} className={inputClass} /></label></div><label className="flex items-center gap-2 text-sm font-bold text-slate-700"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)} /> Aktif</label><button disabled={saving || !label.trim()} className="w-full rounded-xl bg-sky-600 py-3 text-xs font-extrabold text-white disabled:opacity-40">{saving ? "Menyimpan..." : "Simpan"}</button></form></Modal>; };
